export const CardsActionTypes = {
  SET_CURRENT_SUBJECT: 'SET_CURRENT_SUBJECT',
  ADD_CARD: 'ADD_CARD',
  DROP_CARD: 'DROP_CARD',
  ADD_SUBJECT: 'ADD_SUBJECT',
  DROP_SUBJECT: 'DROP_SUBJECT',
  SET_ALL_CARDS: 'SET_ALL_CARDS'
};
